---
title: "Del 1: Laktatterskel"
format: html
editor_options: 
  chunk_output_type: console
---

# Del 1: Laktatterskel

Vi valgte å bruke cyclingstudy datasettet med tanke på at vi ikke testet laktatprofiler under reliabilitets-prosjektet vårt. Dette datasettet inneholder data fra 21 forsøkspersoner, der de fleste har gjennomført en laktatprofil på fire ulike tidspunkt: pre, meso1, meso2 og meso3. 

```{r}

library(tidyverse)
library(exscidata)
library(gt)
library(modelr)
library(gtExtras)

# Importert datasett

data("cyclingstudy")
data("hypertrophy")

```

Nytt forsøk onsdag kveld: 

```{r}

# Laktatprofil til forsøksperson 10 "Pre" test: 

cyclingstudy %>%
  select(subject, group, timepoint, lac.125:lac.375) %>%
  filter(timepoint == "pre", subject == 10) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.225:lac.375) %>%  
  filter(!is.na(lactate)) %>%
  ggplot(aes(watt, lactate, group = subject))  + 
  geom_line(lty = 2) +
  geom_point(shape = 21, fill = "lightblue", size = 2.5) +
  geom_hline(yintercept = 4, color = "red") +
  geom_hline(yintercept = 2, color = "red") +
  geom_vline(xintercept = 341.5, color = "blue")

```

```{r}

# Laktatprofil til forsøksperson 10 "Meso1" test: 

cyclingstudy %>%
  select(subject, group, timepoint, lac.125:lac.375) %>%
  filter(timepoint == "meso1", subject == 10) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.225:lac.375) %>%  
  filter(!is.na(lactate)) %>% 
  ggplot(aes(watt, lactate, group = subject))  + 
  geom_line(lty = 2) +
  geom_point(shape = 21, fill = "lightblue", size = 2.5) +
  geom_hline(yintercept = 4, color = "red") +
  geom_hline(yintercept = 2, color = "red")
  geom_vline(xintercept = 340, color = "blue")


```

```{r}

laktatterskel <- cyclingstudy %>% 
  select(subject, group, timepoint, lac.125:lac.375) %>%
  filter(timepoint == "pre", subject == 10) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.225:lac.375) %>%  
  filter(!is.na(lactate))

m1 <- lm(lactate ~ watt, data = laktatterskel)

m2 <- lm(lactate ~ poly(watt, 2, raw = TRUE), data = laktatterskel)

m3 <- lm(lactate ~ poly(watt, 3, raw = TRUE), data = laktatterskel)

```







## Laktatterskel pre-test

```{r}

library(tidyverse)
library(exscidata)

data("cyclingstudy")

Laktatterskel <- cyclingstudy %>%
  select(subject, group, timepoint, lac.125:lac.375) %>%
  filter(timepoint == "pre", subject == 10) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.125:lac.375) %>%
  filter(!is.na(lactate))

mod_laktatterskel <- lm(lactate ~ poly(watt, 3, raw = TRUE), data = Laktatterskel)

Laktatterskel %>% 
  ggplot(aes(watt, lactate, group = subject)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE, formula = y ~ poly(x, 3), color = "#4daf4a")

wattdata <- data.frame(watt = seq(from = 125, to = 375, by = 0.1))

wattdata$pred <- predict(mod_laktatterskel, newdata = wattdata) 

lactate.pre <- wattdata %>% 
  filter(abs(pred - 2) == min(abs(pred - 2)) |
           abs(pred - 4) == min(abs(pred - 4))) %>% 
  mutate(timepoint = "pre",
         lactate = "2mmol")

lactate.pre[2, 4] <- "4mmol" 

```


## Meso 1 
```{r}

Laktatterskel.meso1 <- cyclingstudy %>%
  select(subject, group, timepoint, lac.125:lac.375) %>%
  filter(timepoint == "meso1", subject == 10) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.125:lac.375) %>%
  filter(!is.na(lactate))

mod_laktatterskel.meso1 <- lm(lactate ~ poly(watt, 3, raw = TRUE), data = Laktatterskel.meso1)

Laktatterskel.meso1 %>% 
  ggplot(aes(watt, lactate, group = subject)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE, formula = y ~ poly(x, 3), color = "#4daf4a")

wattdata.meso1 <- data.frame(watt = seq(from = 125, to = 375, by = 0.1))

wattdata.meso1$pred <- predict(mod_laktatterskel.meso1, newdata = wattdata.meso1)

lactate.meso1 <- wattdata.meso1 %>% 
  filter(abs(pred - 2) == min(abs(pred - 2)) | 
           abs(pred - 4) == min(abs(pred - 4))) %>% 
  mutate(timepoint = "meso1",
         lactate = "2mmol")

lactate.meso1[2, 4] <- "4mmol"

```

## Meso 2

```{r}
Laktatterskel.meso2 <- cyclingstudy %>%
  select(subject, group, timepoint, lac.125:lac.375) %>%
  filter(timepoint == "meso2", subject == 10) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.125:lac.375) %>%
  filter(!is.na(lactate))

mod_laktatterskel.meso2 <- lm(lactate ~ poly(watt, 3, raw = TRUE), data = Laktatterskel.meso2)

Laktatterskel.meso2 %>% 
  ggplot(aes(watt, lactate, group = subject)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE, formula = y ~ poly(x, 3), color = "#4daf4a")

wattdata.meso2 <- data.frame(watt = seq(from = 125, to = 375, by = 0.1))

wattdata.meso2$pred <- predict(mod_laktatterskel.meso2, newdata = wattdata.meso2)

lactate.meso2 <- wattdata.meso2 %>% 
  filter(abs(pred - 2) == min(abs(pred - 2)) |
           abs(pred - 4) == min(abs(pred - 4))) %>% 
  mutate(timepoint = "meso2",
         lactate = "2mmol")

lactate.meso2[2, 4] <- "4mmol" 

```

## Meso 3

```{r}
Laktatterskel.meso3 <- cyclingstudy %>%
  select(subject, group, timepoint, lac.125:lac.375) %>%
  filter(timepoint == "meso3", subject == 10) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.125:lac.375) %>%
  filter(!is.na(lactate)) 

mod_laktatterskel.meso3 <- lm(lactate ~ poly(watt, 3, raw = TRUE), data = Laktatterskel.meso3)

Laktatterskel.meso3 %>% 
  ggplot(aes(watt, lactate, group = subject)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE, formula = y ~ poly(x, 3), color = "#4daf4a")

wattdata.meso3 <- data.frame(watt = seq(from = 125, to = 375, by = 0.1))

wattdata.meso3$pred <- predict(mod_laktatterskel.meso3, newdata = wattdata.meso3)

lactate.meso3 <- wattdata.meso3 %>% 
  filter(abs(pred - 2) == min(abs(pred - 2)) |
           abs(pred - 4) == min(abs(pred - 4))) %>% 
  mutate(timepoint = "meso3",
         lactate = "2mmol")

lactate.meso3[2, 4] <- "4mmol"

```

```{r}

full_data <- lactate.pre %>% 
  full_join(lactate.meso1) %>% 
  full_join(lactate.meso2) %>% 
  full_join(lactate.meso3)

full_data_rel <- full_data %>% 
  select(-pred) %>% 
  pivot_wider(names_from = timepoint,
              values_from = watt) %>% 
  mutate(diff1 = pre - meso1,
         diff2 = meso1 - meso2,
         diff3 = meso2 - meso3) %>% 
  group_by(lactate) %>% 
  summarise(s = sd(c(diff1, diff2, diff3)),
            m = mean(c(pre, meso1, meso2, meso3)),
            te = s / sqrt(2),
            cv = 100 * (te / m))

gt(full_data_rel)

```



```{r}

#| echo: false
#| warning: false
#| message: false
#| label: "tbl-lt"
#| tbl-cap: "**Calculated Lactate Threshold**"

#Tabellen viser laktatterskel

cyclingstudy %>% 
  select(subject, group, timepoint, lac.125:lac.375) %>% 
  pivot_longer(names_to = "x",
               values_to = "lactate",
               names_transform = list(x = as.numeric),
               cols = lac.125:lac.375) %>%
  filter(!is.na(lactate)) %>% 
  group_by(subject, timepoint) %>% 
  nest() %>% 
  mutate(model = map(data, subject_model),
         watt_range = list(watt = seq(from = 125, to = 375, by = 0.1)),
         df = map(watt_range, df_fun),
         pred = map2(df, model, add_predictions)) %>% 
  unnest(pred) %>% 
  filter(abs(pred - 4) == min(abs(pred - 4)) |
           abs(pred - 2) == min(abs(pred - 2))) %>% 
  select(subject, timepoint, x, pred) %>% 
  mutate(lactate = if_else(pred > 3, "ana", "aer")) %>% 
  select(-pred) %>% 
  rename(watt = x) %>% 
  pivot_wider(names_from = c(timepoint, lactate),
              values_from = watt) %>% 
  select(subject, pre_aer, meso1_aer, meso2_aer, meso3_aer, pre_ana, meso1_ana, meso2_ana, meso3_ana) %>% 
  filter(subject <= 4) %>% 
  gt() %>% 
  tab_spanner(columns = pre_aer:meso3_aer, label = "LT at 2 mmol*L") %>% 
  tab_spanner(columns = pre_ana:meso_ana, label = "LT at 4 mmol*L") %>%
  fmt_number(columns = pre_aer:meso_ana, decimals = 0) %>% 
  gt_add_divider(columns = meso3_aer, color = "grey", style = "dotted") %>% 
  cols_label(subject = "Subject",
             pre_aer = "Pre",
             meso1_aer = "Meso1",
             meso2_aer = "Meso2",
             meso3_aer = "Meso3",
             pre_ana = "Pre",
             meso1_ana = "Meso1",
             meso2_ana = "Meso2",
             meso3_ana = "Meso3") %>% 
  tab_footnote(footnote = "Vis de fire første radene i datasettet") %>% 
  tab_footnote(footnote = "forkortelser: LT, laktatterskel")
  

  

```


```{r}

library(tidyverse)
library(exscidata)

cyclingstudy %>% 
  select(subject, group, timepoint, lac.225:lac.375) %>%
  filter(timepoint == "pre", subject == 10) %>% 
  pivot_longer(names_to = "watt",
               values_to = "lactate",
               names_prefix = "lac",
               names_transform = list(watt = as.numeric),
               cols = lac.225:lac.375) %>%
  filter(!is.na(lactate)) %>% 
  ggplot(aes(watt, lactate, group = subject)) +
  geom_line(lty = 2) + 
  geom_point(shape = 21, fill = "green", size = 2.5) 

cyclingstudy %>% 
  select(subject, group, timepoint, lac.225:lac.375) %>%
  filter(timepoint == "pre", subject == 10) %>% 
  pivot_longer(names_to = "watt",
               values_to = "lactate",
               names_prefix = "lac",
               names_transform = list(watt = as.numeric),
               cols = lac.225:lac.375) %>%
  filter(!is.na(lactate)) %>% 
  ggplot(aes(watt, lactate, group = subject)) +
  geom_line(lty = 2) + 
  geom_point(shape = 21, fill = "green", size = 2.5) +
  geom_hline(yintercept = 4, color = "red") +
  geom_vline(xintercept = 341.5, color = "blue")



```

```{r}
library(ggtext)

cyclingstudy %>%
  select(subject, group, timepoint, lac.225:lac.375) %>%
  filter(timepoint == "pre", subject == 10) %>%
  pivot_longer(names_to = "watt", 
               values_to = "lactate", 
               names_prefix = "lac.",
               names_transform = list(watt = as.numeric),
               cols = lac.225:lac.375) %>%
  filter(!is.na(lactate)) %>%
  ggplot(aes(watt, lactate, group = subject))  + 
  geom_line(lty = 2) +
  geom_point(shape = 21, fill = "lightblue", size = 2.5) +
  geom_hline(yintercept = 4, color = "red") +
  geom_vline(xintercept = 341.5, color = "blue") +
  geom_smooth(method = "lm", se = FALSE, formula = y ~ x, color = "#e41a1c") +
  geom_smooth(method = "lm", se = FALSE, formula = y ~ poly(x, 2), color = "#377eb8") +
  geom_smooth(method = "lm", se = FALSE, formula = y ~ poly(x, 3), color = "#4daf4a") +

  labs(subtitle = "Modelling the lactate-workload relationship as<br>
       <span style = 'color: #377eb8;'>A second degree polynomial</span><br>
       <span style = 'color: #4daf4a;'>A third degree polynomial</span><br>
       <span style = 'color: #e41a1c;'>A straight line</span>") +
  theme(plot.subtitle = element_markdown())
  


```

